# Fonts
font=FiraCode Nerd Font:size=10
font-bold=FiraCode Nerd Font:weight=700:size=10
font-italic=FiraCode Nerd Font:slant=italic:size=10
font-bold-italic=FiraCode Nerd Font:weight=bold:slant=italic:size=10
line-height=14

# Window
initial-window-size-pixels=1024x600
pad=10x10

[scrollback]
lines=5000

[cursor]
style=block
blink=yes
blink-rate=500

[colors]
alpha=0.95
foreground=ffffff
background=121212

regular0=545454  # black
regular1=FF5370  # red
regular2=C3E88D  # green
regular3=F0C674  # yellow
regular4=82AAFF  # blue
regular5=C792EA  # magenta
regular6=9CDCFE  # cyan
regular7=EEFFFF  # white
