[window]
decorations = "Full"
opacity = 0.8
blur = true
dynamic_title = true
padding = { x = 5, y = 5 }

[scrolling]
history = 30000

[font]
size = 10.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[colors]
primary = { background = "#090909", foreground = "#ffffff" }
normal = { black = "#000000", red = "#FF5370", green = "#C3E88D", yellow = "#F0C674", blue = "#82AAFF", magenta = "#C792EA", cyan = "#9CDCFE", white = "#EEFFFF" }

[cursor]
style = { shape = "Beam", blinking = "Always" }
